CREATE TABLE BANK_ACCOUNTS (
BANK_ACCOUNT_ID NUMBER NOT NULL PRIMARY KEY,
BANK_ACCOUNT_BALANCE NUMBER(18,2) NOT NULL
);

CREATE TABLE USERS (
USER_ID NUMBER NOT NULL PRIMARY KEY,
BANK_ACCOUNT_ID NUMBER NOT NULL,
FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNTS(BANK_ACCOUNT_ID),
USERNAME VARCHAR2(20 BYTE) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(20 BYTE) NOT NULL
);

CREATE SEQUENCE SEQUENCE_BANK_ACCOUNT_ID INCREMENT BY 1;
CREATE SEQUENCE SEQUENCE_USER_ID INCREMENT BY 1;


/*CREATE PROCEDURE InsertBankAccount (p_BankAccountId NUMBER)
IS BEGIN
INSERT INTO BANK_ACCOUNTS VALUES(p_BankAccountId, 0.00);
END;

CREATE PROCEDURE InsertUser (p_BankAccountId NUMBER, p_UserName VARCHAR2, p_UserPassword VARCHAR2)
IS BEGIN
INSERT INTO USERS VALUES(SEQUENCE_USER_ID.NEXTVAL, p_BankAccountId, p_UserName, p_UserPassword);
END;

CREATE PROCEDURE BankAccountSelectBalance (p_BankAccountId NUMBER)
IS
o_BankAccountBalance NUMBER(18,2);
BEGIN
SELECT BANK_ACCOUNT_BALANCE INTO o_BankAccountBalance FROM BANK_ACCOUNTS WHERE BANK_ACCOUNTS.BANK_ACCOUNT_ID=p_BankAccountId;
END;

CREATE PROCEDURE UserSelect (p_UserName VARCHAR2)
IS
o_UserId NUMBER;
o_BankAccountId NUMBER;
o_UserPassword VARCHAR2(20 BYTE);
BEGIN
SELECT USER_ID, BANK_ACCOUNT_ID, USER_PASSWORD INTO o_userid, o_bankaccountid, o_userpassword
FROM USERS WHERE USERS.USERNAME=p_UserName;
END;

CREATE PROCEDURE UserSelectPassword (p_UserName VARCHAR2)
IS
o_UserPassword VARCHAR2(20 BYTE);
BEGIN
SELECT USER_PASSWORD INTO o_UserPassword FROM BANK_ACCOUNTS WHERE BANK_ACCOUNTS.USERNAME=p_UserName;
END;

CREATE PROCEDURE BankAccountUpdateBalance (p_BankAccountBalance NUMBER, p_BankAccountId NUMBER)
IS BEGIN
UPDATE BANK_ACCOUNTS SET BANK_ACCOUNT_BALANCE=p_BankAccountBalance WHERE BANK_ACCOUNTS.BANK_ACCOUNT_ID=p_BankAccountId;
END;

CREATE PROCEDURE DeleteBankAccount (p_BankAccountId NUMBER)
IS BEGIN
DELETE FROM BANK_ACCOUNTS WHERE BANK_ACCOUNTS.BANK_ACCOUNT_ID=p_BankAccountId;
END;

CREATE PROCEDURE DeleteUser (p_UserId NUMBER)
IS BEGIN
DELETE FROM USERS WHERE USERS.USER_ID=p_UserId;
END;

CREATE PROCEDURE SelectNextBankAccountId
IS
o_NextBankAccountId NUMBER;
BEGIN
SELECT SEQUENCE_BANK_ACCOUNT_ID.NEXTVAL INTO o_nextbankaccountid FROM DUAL;
END;*/