CREATE TABLE BANK_ACCOUNTS (
BANK_ACCOUNT_ID NUMBER NOT NULL PRIMARY KEY,
BANK_ACCOUNT_BALANCE NUMBER(18,2) NOT NULL
);

CREATE TABLE USERS (
USER_ID NUMBER NOT NULL PRIMARY KEY,
BANK_ACCOUNT_ID NUMBER NOT NULL,
FOREIGN KEY (BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNTS(BANK_ACCOUNT_ID),
USERNAME VARCHAR2(20 BYTE) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(20 BYTE) NOT NULL
);

CREATE SEQUENCE SEQUENCE_BANK_ACCOUNT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCE_USER_ID START WITH 1 INCREMENT BY 1;